checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    dependency_paths:
        - lib/

build:
    environment:
        python: '3.7'
        postgresql: false
        redis: false

    dependencies:
        override:
            # Project depends
            - pip install aiodns cchardet ujson aiohttp asyncio beautifulsoup4 rsa
            # Coverage depends
            - pip install pylint>=1.8.1 mypy>=0.580 lxml coverage pytest pytest-cov

    project_setup:
        override:
            - python -m pip install .

    tests:
        override:
            - py-scrutinizer-run
            - command: pylint-run stlib --rcfile=pylintrc
