clone_folder: "C:\\stlib_build"

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PLATFORM: "x86"
          PYTHON: "C:\\Python37"
          PYTHON_VERSION: "3.7"
          PYTHON_ARCH: "32"

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PLATFORM: "x64"
          PYTHON: "C:\\Python37-x64"
          PYTHON_VERSION: "3.7"
          PYTHON_ARCH: "64"

install:
    - "%PYTHON%\\python.exe -m pip install aiodns cchardet ujson aiohttp asyncio beautifulsoup4 build wheel"

build_script:
    - "%PYTHON%\\python.exe -m build"
    - "%PYTHON%\\python.exe -m pip install ."

artifacts:
    - path: 'dist\*.tar.gz'
      name: sdist

    - path: 'dist\*.whl'
      name: wheel
