name: Build
on: [push, workflow_dispatch]

jobs:
  delete-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
  linux-build:
    if: ${{ always() }}
    needs: delete-old-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install build
      - run: ./tools/Linux/dist_script.sh
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: |
            build/*.zip
            dist/
          if-no-files-found: error
          retention-days: 90
  deploy:
    #if: startsWith(github.ref, 'refs/tags/')
    if: ${{ always() }}
    needs: [linux-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            linux/dist/*.whl
