name: Coverage
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }} coverage
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r dev-requirements.txt
      - run: ./tools/Linux/dist_script.sh
      - run: python -m pip install dist/*.whl -v
      - name: Prevent exceeding steam rate limits (waiting 30s)
        run: sleep 30s
      - run: pytest --cov=stlib --cov-report=xml
        env:
          steamid: ${{ secrets.STEAMID }}
          account_name: ${{ secrets.ACCOUNT_NAME }}
          password_raw: ${{ secrets.PASSWORD_RAW }}
          shared_secret: ${{ secrets.SHARED_SECRET }}
          identity_secret: ${{ secrets.IDENTITY_SECRET }}
          api_key: ${{ secrets.API_KEY }}
          LIMITED_ACCOUNT: ${{ secrets.LIMITED_ACCOUNT }}
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
