name: Coverage
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    name: Python ${{ matrix.python-version }} coverage
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install build
      - run: ./tools/Linux/dist_script.sh
      - run: python -m pip install dist/*.whl -v
      - run: python -m pip install pytest pytest-cov pytest-asyncio
      - name: Prevent exceeding steam rate limits (waiting 30s)
        run: sleep 30s
      - run: pytest --cov=stlib --cov-report=xml
        env:
          steamid: ${{ secrets.STEAMID }}
          account_name: ${{ secrets.ACCOUNT_NAME }}
          password_raw: ${{ secrets.PASSWORD_RAW }}
          shared_secret: ${{ secrets.SHARED_SECRET }}
          identity_secret: ${{ secrets.IDENTITY_SECRET }}
          api_key: ${{ secrets.API_KEY }}
          LIMITED_ACCOUNT: ${{ secrets.LIMITED_ACCOUNT }}
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
