name: Coverage
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }} coverage
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r dev-requirements.txt
      - run: ./tools/Linux/dist_script.sh
      - run: python -m pip install dist/*.whl -v
      - name: Prevent exceeding steam rate limits (waiting 30s)
        run: sleep 30s
      - run: pytest --cov=stlib --cov-report=xml
        env:
          steamid: ${{ secrets.STEAMID }}
          account_name: ${{ secrets.ACCOUNT_NAME }}
          password_raw: ${{ secrets.PASSWORD_RAW }}
          shared_secret: ${{ secrets.SHARED_SECRET }}
          identity_secret: ${{ secrets.IDENTITY_SECRET }}
          api_key: ${{ secrets.API_KEY }}
          LIMITED_ACCOUNT: ${{ secrets.LIMITED_ACCOUNT }}
      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
