name: Coverage
on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    name: Python ${{ matrix.python-version }} coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install build
      - run: ./tools/Linux/dist_script.sh
      - run: python -m pip install dist/*.whl -v
      - run: python -m pip install pytest pytest-cov pytest-asyncio
      - run: pytest --cov=stlib --cov-report=xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
