name: Coverage
on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -m pip install build
      - run: ./tools/Linux/dist_script.sh
      - run: python -m pip install dist/*.whl -v
      - run: python -m pip install pytest pytest-cov
      - run: pytest --cov=stlib --cov-report=xml
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
